export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CLEAR_CURRENT_PROJECT = "CLEAR_CURRENT_PROJECT";

export const PROJECT_LOADING = "POST_LOADING";
export const GET_PROJECTS = "GET_POSTS";
export const GET_PROJECT = "GET_POST";
export const ADD_PROJECT = "ADD_POST";
export const DELETE_PROJECT = "DELETE_POST";
export const GET_PERSONS = "GET_PERSONS";
export const PERSONS_LOADING = "PERSONS_LOADING";
export const DELETE_PERSONS = "DELETE_PERSONS";
